name: fruits_hub_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  change_app_package_name: ^1.4.0
  cloud_firestore: ^5.6.2
  equatable: ^2.0.7
  firebase_cloud_firestore: ^5.4.4
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
