// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7sgWeK7jFJ7FvjSHH6UUIQrvWU9Z_ODM',
    appId: '1:574383333204:web:f01922320707e4847472c1',
    messagingSenderId: '574383333204',
    projectId: 'noor-app-4d022',
    authDomain: 'noor-app-4d022.firebaseapp.com',
    storageBucket: 'noor-app-4d022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsEhWTUMd1nvtQr89JGPjn679-UuZeCcU',
    appId: '1:574383333204:android:c58c72b1ca19864a7472c1',
    messagingSenderId: '574383333204',
    projectId: 'noor-app-4d022',
    storageBucket: 'noor-app-4d022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIZQU0i5VhJvlUCkHiRIVYOPPastTTImo',
    appId: '1:574383333204:ios:f07d9d5c08c8f1577472c1',
    messagingSenderId: '574383333204',
    projectId: 'noor-app-4d022',
    storageBucket: 'noor-app-4d022.appspot.com',
    androidClientId: '574383333204-c1ti0uvc7ssov2ndibedbl65r1cnlsbe.apps.googleusercontent.com',
    iosClientId: '574383333204-5ier1scs1nucu2daphj2g6d0qfeu71eh.apps.googleusercontent.com',
    iosBundleId: 'com.moanbm123.fruitshubdashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIZQU0i5VhJvlUCkHiRIVYOPPastTTImo',
    appId: '1:574383333204:ios:edfae98b7a81620e7472c1',
    messagingSenderId: '574383333204',
    projectId: 'noor-app-4d022',
    storageBucket: 'noor-app-4d022.appspot.com',
    androidClientId: '574383333204-c1ti0uvc7ssov2ndibedbl65r1cnlsbe.apps.googleusercontent.com',
    iosClientId: '574383333204-gljm5dnnl3robivrbummlo7sbspmbe5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7sgWeK7jFJ7FvjSHH6UUIQrvWU9Z_ODM',
    appId: '1:574383333204:web:f19b05744327f5bf7472c1',
    messagingSenderId: '574383333204',
    projectId: 'noor-app-4d022',
    authDomain: 'noor-app-4d022.firebaseapp.com',
    storageBucket: 'noor-app-4d022.appspot.com',
  );
}
