import 'package:flutter/material.dart';
import 'package:fruits_hub_dashboard/features/advertisement/domain/entities/advertisement_entity.dart';

List<AdvertisementEntity> dummyAdvertisements = [
  AdvertisementEntity(
    id: '1',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Summer Sale',
    titleArabic: 'تخفيضات الصيف',
    discount: 20,
    backgroundBanner: Colors.orangeAccent,
    pageRoute: '/summer-sale',
  ),
  AdvertisementEntity(
    id: '2',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Buy One Get One',
    titleArabic: 'اشترِ واحدة واحصل على الأخرى مجانًا',
    discount: 50,
    backgroundBanner: Colors.blueAccent,
    pageRoute: '/bogo-offer',
  ),
  AdvertisementEntity(
    id: '3',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Weekend Flash Sale',
    titleArabic: 'تخفيضات نهاية الأسبوع السريعة',
    discount: 30,
    backgroundBanner: Colors.redAccent,
    pageRoute: '/flash-sale',
  ),
  AdvertisementEntity(
    id: '4',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Summer Sale',
    titleArabic: 'تخفيضات الصيف',
    discount: 20,
    backgroundBanner: Colors.orangeAccent,
    pageRoute: '/summer-sale',
  ),
  AdvertisementEntity(
    id: '5',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Buy One Get One',
    titleArabic: 'اشترِ واحدة واحصل على الأخرى مجانًا',
    discount: 50,
    backgroundBanner: Colors.blueAccent,
    pageRoute: '/bogo-offer',
  ),
  AdvertisementEntity(
    id: '6',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Weekend Flash Sale',
    titleArabic: 'تخفيضات نهاية الأسبوع السريعة',
    discount: 30,
    backgroundBanner: Colors.redAccent,
    pageRoute: '/flash-sale',
  ),
  AdvertisementEntity(
    id: '7',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Summer Sale',
    titleArabic: 'تخفيضات الصيف',
    discount: 20,
    backgroundBanner: Colors.orangeAccent,
    pageRoute: '/summer-sale',
  ),
  AdvertisementEntity(
    id: '8',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Buy One Get One',
    titleArabic: 'اشترِ واحدة واحصل على الأخرى مجانًا',
    discount: 50,
    backgroundBanner: Colors.blueAccent,
    pageRoute: '/bogo-offer',
  ),
  AdvertisementEntity(
    id: '9',
    imageUrl: 'https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvam9iNjgwLTE2Ni1wLWwxZGJ1cTN2LnBuZw.png',
    imageFile: null,
    titleEnglish: 'Weekend Flash Sale',
    titleArabic: 'تخفيضات نهاية الأسبوع السريعة',
    discount: 30,
    backgroundBanner: Colors.redAccent,
    pageRoute: '/flash-sale',
  ),
];